server:
  port: 9999

endpoint:
  url: localhost:9999

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
      notificationClientService:
        connectTimeout: 2000
        readTimeout: 2000

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      slowCallRateThreshold: 70
      slowCallDurationThreshold: 2000
      permittedNumberOfCallsInHalfOpenState: 20  # 총 요청 수의 5%
      maxWaitDurationInHalfOpenState: 2000
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 40  # 예를 들어 총 요청 수가 40일 때 5%는 2
      minimumNumberOfCalls: 5
      registerHealthIndicator: true
      waitDurationInOpenState: 3000


  instances:
    getApiClientResponse:
      baseConfig: default
logging:
  level:
    # Set logging level for Resilience4j and Circuit Breaker classes
    io.github.resilience4j: DEBUG
    # Adjust specific Circuit Breaker logging as needed
    io.github.resilience4j.circuitbreaker: DEBUG
    # Optionally, adjust logging levels for other relevant packages
    org.springframework.web.client.RestTemplate: DEBUG
